#!/bin/bash
ttystring=$(tty)
clk_tck=$(getconf CLK_TCK)

printf "%5s %-8s %8s %s\n" "PID" "TTY" "TIME" "CMD"

find /proc -maxdepth 1 -type d -regex '^/proc/[0-9]+$' -print0 | while read -d $'\0' process
do
    # Make sure it still exists
    if [[ ! -e $process/stat ]]; then continue; fi

    # Check if EUID=euid
    euid=$(awk '/^Uid:/{print $3; exit 0}' ${process}/status)
    if [[ ! "$EUID" = "$euid" ]]; then continue; fi

    # Parse stat
    read pid comm tty_nr utime stime <<< $(cut -d' ' -f1,2,7,14,15 ${process}/stat)
    comm=${comm:1:((${#comm}-2))}

    # Parse TTY information
    if [[ "$tty_nr" =~ "0" ]]; then
        tty="?"
    else
        tty_nr=$(ttyParse $tty_nr)
        read tty_maj tty_min <<< "$tty_nr"
        case "$tty_maj" in
            0)
                tty="?"
                ;;
            136)
                tty="pts/"$tty_min
                ;;
            4)
                tty="tty"$tty_min
                ;;
        esac
    fi
    # Only show process from same controlling terminal
    if [[ ! "$ttystring" =~ "$tty" ]]; then continue; fi

    total_time=$((($utime+$stime)/$clk_tck))
    seconds=$((total_time%60))
    minutes=$((total_time/60%60))
    hours=$((total_time/60/60))
    printf "%5s %-8s %02d:%02d:%02d %s\n" "$pid" "$tty" "$hours" "$minutes" "$seconds" "$comm"
    #printf "%5s %-8s  %s\n" "$pid" "$tty" "time" "$comm"
done

