#!/bin/bash

clk_tck=$(getconf CLK_TCK)

printf "%5s %-8s %8s %s\n" "PID" "TTY" "TIME" "CMD"

find /proc -maxdepth 1 -type d -regex '^/proc/[0-9]+$' -print0 | while read -d $'\0' process
do
    #read pid comm tty_nr <<< $(awk '{print $1; print $2; print $7}' ${process}/stat)
    if [[ ! -e $process/stat ]]; then continue; fi
    read pid comm tty_nr utime stime <<< $(cut -d' ' -f1,2,7,14,15 ${process}/stat)
    comm=${comm:1:((${#comm}-2))}

    total_time=$((($utime+$stime)/$clk_tck))
    seconds=$((total_time%60))
    minutes=$((total_time/60%60))
    hours=$((total_time/60/60))
    #time=$(printf "%02d:%02d:%02d" "$hours" "$minutes" "$seconds")

    if [[ "$tty_nr" =~ "^0$" ]]; then
        tty="?"
    else
        tty_nr=$(ttyParse $tty_nr)
        read tty_maj tty_min <<< "$tty_nr"
        case "$tty_maj" in
            0)
                tty="?"
                ;;
            136)
                tty="pts/"$tty_min
                ;;
            4)
                tty="tty"$tty_min
                ;;
        esac
    fi

    printf "%5s %-8s %02d:%02d:%02d %s\n" "$pid" "$tty" "$hours" "$minutes" "$seconds" "$comm"
    #printf "%5s %-8s %8s %s\n" "$pid" "$tty" "$time" "$comm"
done

