#!/bin/bash

while getopts "p:U:eC:" opt; do
    case "$opt" in
    p)
        new_pps $@
        exit 0
        ;;
    U)
        ups $OPTARG
        exit 0
        ;;
    e)
        eps
        exit 0
        ;;
    C)
        cps $OPTARG
        exit 0
        ;;
    esac
done

# Default behavior
dps
exit 0
