#!/bin/bash

echo "PPS"

pid=$1
name=`grep Name: /proc/$pid/status`
state=`grep State: /proc/$pid/status`
stat_file=`cat /proc/$pid/stat`
read -r -a stat <<< "$stat_file"
uptime_file=`cat /proc/uptime`
read -r -a uptime <<< "$uptime_file"

tty_nr="${stat[6]}" # Get the TTY
starttime="${stat[21]}" # Get the time the process was started after system boot in clock ticks.
clk_tck=`getconf CLK_TCK` # Get the clock tick.

uptime="${uptime[0]}" # Get the system uptime.
uptime=${uptime%.*} # Remove decimal place from system uptime.
cur_time=`date +%s` # Get current time in seconds.


printf "PID: %i\n" $pid
echo "$name"
echo "$state"
printf "tty_nr: %i\n" $tty_nr
printf "starttime: %i\n" $starttime
printf "Clock Tick: %i\n" $clk_tck
printf "System Uptime: %i\n" $uptime
printf "Current Time: %li\n" $cur_time

proc_uptime=$(($uptime-($starttime/$clk_tck)))

printf "Running Time: %i\n" $(($proc_uptime/60))

diff=$(($cur_time-$proc_uptime))

date -d @$diff
