#!/bin/bash

myprogram='myps'
realprogram='ps'

while getopts "p:U:eC:" opt; do
    case "$opt" in
    p)
        myprogram='myps -p '$OPTARG
        realprogram='ps -p '$OPTARG
        ;;
    U)
        myprogram='myps -U '$OPTARG
        realprogram='ps -U '$OPTARG
        ;;
    e)
        myprogram='myps -e'
        realprogram='ps -e'
        ;;
    C)
        myprogram='myps -C '$OPTARG
        realprogram='ps -C '$OPTARG
        ;;
    esac
done

$myprogram > myoutput
$realprogram > realoutput
diff -y myoutput realoutput
rm myoutput realoutput
