#!/bin/bash

while getopts "p:U:eC:" opt; do
    case "$opt" in
    p)
        myprogram='pps '$OPTARG
        realprogram='ps -p '$OPTARG
        ;;
    U)
        myprogram='ups '$OPTARG
        realprogram='ps -U '$OPTARG
        ;;
    e)
        myprogram='eps'
        realprogram='ps -e'
        ;;
    C)
        myprogram='cps '$OPTARG
        realprogram='ps -C '$OPTARG
        ;;
    esac

    $myprogram > myoutput
    $realprogram > realoutput
    diff -y myoutput realoutput
    rm myoutput realoutput
    exit 0
done
