#!/bin/bash

pid=$1
stat_file=`cat /proc/$pid/stat`
read -r -a stat <<< "$stat_file"

clk_tck=`getconf CLK_TCK` # Get the clock tick.

utime="${stat[13]}" # Time in user mode.
stime="${stat[14]}" # Time in kenel mode.

total_time=$((($utime+$stime)/$clk_tck))

seconds=$((total_time%60))
minutes=$((total_time/60%60))
hours=$((total_time/60/60))

printf "%02d:%02d:%02d\n" $hours $minutes $seconds
